POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
  "email": "livininthesunshine39@hotmail.com",
  "name": "Tiny Tim22",
  "password": "toodles22",
  "role": "admin"
}

###

POST http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{

"email": "livininthesunshine36@hotmail.com",
"password": "toodles22"
}

###

POST http://localhost:3000/api/logout HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/api/blog HTTP/1.1
content-type: application/json


{
"title": "cachislamarsalada",
"content": "akngkjsebgesg",
"authorId": 2866
}

### Con token

POST http://localhost:3000/api/blog HTTP/1.1
content-type: application/json

{
"title": "Hallellujah",
"content": "akngkjsebgesg"
}

###

GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/blog

###

PUT http://localhost:3000/api/blog/1557 HTTP/1.1
content-type: application/json

{
  "title": "Rickrolled",
  "content": "never gonna get you down"
}

###

PATCH http://localhost:3000/api/blog/1557

###

GET http://localhost:3000/api/blog/1558

###

PATCH http://localhost:3000/api/blog/1557/recover 

###

PATCH http://localhost:3000/api/blog/1560/liked

###

GET http://localhost:3000/api/blog/2963/byauthor

###

PUT http://localhost:3000/api/users/2800 HTTP/1.1
content-type: application/json

{
  "email":"toto67@gmail.com",
  "name": "Big Sam"
}

###

PATCH http://localhost:3000/api/users/2833/ban

###

PATCH http://localhost:3000/api/users/2833/unban

###

PATCH http://localhost:3000/api/blog/1558/counter

###

DELETE http://localhost:3000/api/blog/1557/final

###
DELETE http://localhost:3000/api/blog

###
DELETE http://localhost:3000/api/users

###

GET http://localhost:3000/api/blog/1558/popularity

###

GET http://localhost:3000/api/blog/testing

###

DELETE http://localhost:3000/api/likes