POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
  "email": "livininthesunshine36@hotmail.com",
  "name": "Tiny Tim22",
  "password": "toodles22",
  "role": "admin"
}

###

POST http://localhost:3000/api/blog HTTP/1.1
content-type: application/json

{

"title": "cachislamarsalada",
"authorId": 2191

}

###

POST http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{

"email": "livininthesunshine36@hotmail.com",
"password": "toodles22"

}

###

GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/blog

###

PUT http://localhost:3000/api/blog/1334 HTTP/1.1
content-type: application/json

{
  "content": "never gonna gget you down"
}

###

DELETE http://localhost:3000/api/blog/7

###

GET http://localhost:3000/api/blog/1

###

PATCH http://localhost:3000/api/blog/7/recover 

###

PATCH http://localhost:3000/api/blog/1/liked


###

GET http://localhost:3000/api/blog/1714/byauthor

###

PUT http://localhost:3000/api/users/48 HTTP/1.1
content-type: application/json

{
  "email":"toto67@gmail.com",
  "name": "Big Sam"
}

###

PATCH http://localhost:3000/api/users/1/ban

###

PATCH http://localhost:3000/api/users/1/unban

###

PATCH http://localhost:3000/api/blog/300/counter

###

DELETE http://localhost:3000/api/blog/9/final

###
DELETE http://localhost:3000/api/blog

###
DELETE http://localhost:3000/api/users

###
DELETE http://localhost:3020/api/blog

###
DELETE http://localhost:3020/api/users

###
DELETE http://localhost:3010/api/blog

###
DELETE http://localhost:3010/api/users

###

GET http://localhost:3020/api/users

###

GET http://localhost:3020/api/blog

###

GET http://localhost:3010/api/users

###

GET http://localhost:3010/api/blog

###

GET http://localhost:3000/api/blog/300/popularity

###

GET http://localhost:3000/api/blog/testing