POST http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{

"email": "livininthesunshine39@hotmail.com",
"password": "toodles22"
}

###

POST http://localhost:3000/api/logout HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
  "email": "deetznuts37@gmail.com",
  "name": "Deetz Nuts5",
  "password": "deetznuts",
  "role": "simpleUser"
}

### Con token

POST http://localhost:3000/api/blog HTTP/1.1
content-type: application/json

{
"title": "Hallellujah",
"content": "akngkjsebgesg"
}

###

GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/blog

###

GET http://localhost:3000/api/blog/1558

###

GET http://localhost:3000/api/blog/2963/byauthor

###

GET http://localhost:3000/api/blog/testing

###

PUT http://localhost:3000/api/blog/1562 HTTP/1.1
content-type: application/json

{
  "title": "Rickrolled",
  "content": "never gonna get you down"
}

###

PUT http://localhost:3000/api/users/2969 HTTP/1.1
content-type: application/json

{
  "email":"toto67@gmail.com",
  "name": "Big Sam"
}

###

PATCH http://localhost:3000/api/blog/1562/popularity

###

PATCH http://localhost:3000/api/blog/1557/delete

###

PATCH http://localhost:3000/api/blog/1557/recover 

###

PATCH http://localhost:3000/api/blog/1562/liked

###

PATCH http://localhost:3000/api/blog/1562/disliked

###

PATCH http://localhost:3000/api/users/2963/ban

###

PATCH http://localhost:3000/api/users/2963/unban

###

PATCH http://localhost:3000/api/blog/1558/counter

###

DELETE http://localhost:3000/api/blog/1561/final

###
DELETE http://localhost:3000/api/blog

###
DELETE http://localhost:3000/api/users

###

DELETE http://localhost:3000/api/likes